config/routes.rb
Whoisbetter::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources  :authentications
  resources  :votes
  resources  :games
  resources  :teams
  resources  :sports
  resources  :league_types
  resources  :sport_types
  root :to => "home#index"

end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/sport_type.rb
class SportType < ActiveRecord::Base
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  # GET /sports
  # GET /sports.xml
  def index
    @sports = Sport.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sports }
    end
  end

  # GET /sports/1
  # GET /sports/1.xml
  def show
    @sport = Sport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sport }
    end
  end

  # GET /sports/new
  # GET /sports/new.xml
  def new
    @sport = Sport.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sport }
    end
  end

  # GET /sports/1/edit
  def edit
    @sport = Sport.find(params[:id])
  end

  # POST /sports
  # POST /sports.xml
  def create
    @sport = Sport.new(params[:sport])

    respond_to do |format|
      if @sport.save
        format.html { redirect_to(@sport, :notice => 'Sport was successfully created.') }
        format.xml  { render :xml => @sport, :status => :created, :location => @sport }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sports/1
  # PUT /sports/1.xml
  def update
    @sport = Sport.find(params[:id])

    respond_to do |format|
      if @sport.update_attributes(params[:sport])
        format.html { redirect_to(@sport, :notice => 'Sport was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.xml
  def destroy
    @sport = Sport.find(params[:id])
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to(sports_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :league %><br />
    <%= f.text_field :league %>
  </div>
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.text_field :icon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1>Listing sports</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Sport</th>
    <th>League</th>
    <th>Icon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sports.each do |sport| %>
  <tr>
    <td><%= sport.name %></td>
    <td><%= sport.sport %></td>
    <td><%= sport.league %></td>
    <td><%= sport.icon %></td>
    <td><%= link_to 'Show', sport %></td>
    <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
    <td><%= link_to 'Destroy', sport, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sport.name %>
</p>

<p>
  <b>Sport:</b>
  <%= @sport.sport %>
</p>

<p>
  <b>League:</b>
  <%= @sport.league %>
</p>

<p>
  <b>Icon:</b>
  <%= @sport.icon %>
</p>


<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>