config/routes.rb
Whoisbetter::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources  :authentications
  resources  :votes
  resources  :games
  resources  :teams
  resources  :sports
  resources  :league_types
  resources  :sport_types
  root :to => "home#index"

end

app/controllers/league_types_controller.rb
class LeagueTypesController < ApplicationController
  # GET /league_types
  # GET /league_types.xml
  def index
    @league_types = LeagueType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @league_types }
    end
  end

  # GET /league_types/1
  # GET /league_types/1.xml
  def show
    @league_type = LeagueType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @league_type }
    end
  end

  # GET /league_types/new
  # GET /league_types/new.xml
  def new
    @league_type = LeagueType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @league_type }
    end
  end

  # GET /league_types/1/edit
  def edit
    @league_type = LeagueType.find(params[:id])
  end

  # POST /league_types
  # POST /league_types.xml
  def create
    @league_type = LeagueType.new(params[:league_type])

    respond_to do |format|
      if @league_type.save
        format.html { redirect_to(@league_type, :notice => 'League type was successfully created.') }
        format.xml  { render :xml => @league_type, :status => :created, :location => @league_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @league_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /league_types/1
  # PUT /league_types/1.xml
  def update
    @league_type = LeagueType.find(params[:id])

    respond_to do |format|
      if @league_type.update_attributes(params[:league_type])
        format.html { redirect_to(@league_type, :notice => 'League type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @league_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /league_types/1
  # DELETE /league_types/1.xml
  def destroy
    @league_type = LeagueType.find(params[:id])
    @league_type.destroy

    respond_to do |format|
      format.html { redirect_to(league_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/league_types_helper.rb
module LeagueTypesHelper
end

app/views/league_types/_form.html.erb
<%= form_for(@league_type) do |f| %>
  <% if @league_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league_type.errors.count, "error") %> prohibited this league_type from being saved:</h2>

      <ul>
      <% @league_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/league_types/edit.html.erb
<h1>Editing league_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @league_type %> |
<%= link_to 'Back', league_types_path %>

app/views/league_types/index.html.erb
<h1>Listing league_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @league_types.each do |league_type| %>
  <tr>
    <td><%= league_type.name %></td>
    <td><%= link_to 'Show', league_type %></td>
    <td><%= link_to 'Edit', edit_league_type_path(league_type) %></td>
    <td><%= link_to 'Destroy', league_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New League type', new_league_type_path %>

app/views/league_types/new.html.erb
<h1>New league_type</h1>

<%= render 'form' %>

<%= link_to 'Back', league_types_path %>

app/views/league_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @league_type.name %>
</p>


<%= link_to 'Edit', edit_league_type_path(@league_type) %> |
<%= link_to 'Back', league_types_path %>