config/routes.rb
Whoisbetter::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources  :authentications
  resources  :votes
  resources  :games
  resources  :teams
  resources  :sports
  resources  :league_types
  resources  :sport_types
  root :to => "home#index"

end

app/controllers/sport_types_controller.rb
class SportTypesController < ApplicationController
  # GET /sport_types
  # GET /sport_types.xml
  def index
    @sport_types = SportType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sport_types }
    end
  end

  # GET /sport_types/1
  # GET /sport_types/1.xml
  def show
    @sport_type = SportType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sport_type }
    end
  end

  # GET /sport_types/new
  # GET /sport_types/new.xml
  def new
    @sport_type = SportType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sport_type }
    end
  end

  # GET /sport_types/1/edit
  def edit
    @sport_type = SportType.find(params[:id])
  end

  # POST /sport_types
  # POST /sport_types.xml
  def create
    @sport_type = SportType.new(params[:sport_type])

    respond_to do |format|
      if @sport_type.save
        format.html { redirect_to(@sport_type, :notice => 'Sport type was successfully created.') }
        format.xml  { render :xml => @sport_type, :status => :created, :location => @sport_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sport_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sport_types/1
  # PUT /sport_types/1.xml
  def update
    @sport_type = SportType.find(params[:id])

    respond_to do |format|
      if @sport_type.update_attributes(params[:sport_type])
        format.html { redirect_to(@sport_type, :notice => 'Sport type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sport_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sport_types/1
  # DELETE /sport_types/1.xml
  def destroy
    @sport_type = SportType.find(params[:id])
    @sport_type.destroy

    respond_to do |format|
      format.html { redirect_to(sport_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sport_types_helper.rb
module SportTypesHelper
end

app/views/sport_types/_form.html.erb
<%= form_for(@sport_type) do |f| %>
  <% if @sport_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport_type.errors.count, "error") %> prohibited this sport_type from being saved:</h2>

      <ul>
      <% @sport_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sport_types/edit.html.erb
<h1>Editing sport_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport_type %> |
<%= link_to 'Back', sport_types_path %>

app/views/sport_types/index.html.erb
<h1>Listing sport_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sport_types.each do |sport_type| %>
  <tr>
    <td><%= sport_type.name %></td>
    <td><%= link_to 'Show', sport_type %></td>
    <td><%= link_to 'Edit', edit_sport_type_path(sport_type) %></td>
    <td><%= link_to 'Destroy', sport_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sport type', new_sport_type_path %>

app/views/sport_types/new.html.erb
<h1>New sport_type</h1>

<%= render 'form' %>

<%= link_to 'Back', sport_types_path %>

app/views/sport_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sport_type.name %>
</p>


<%= link_to 'Edit', edit_sport_type_path(@sport_type) %> |
<%= link_to 'Back', sport_types_path %>